In [1]:
import json
import numpy as np
from sklearn.naive_bayes import GaussianNB

In [2]:
gnb = GaussianNB()

In [4]:
from sklearn import datasets
iris = datasets.load_iris()

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [8]:
y_pred = gnb.fit(iris.data, iris.target).predict(iris.data)
print(y_pred)
print("Number of mislabeled points out of a total %d points : %d" % (iris.data.shape[0],(iris.target != y_pred).sum()))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Number of mislabeled points out of a total 150 points : 6


## using sklearn gnb for prediction

In [11]:
train = json.load(open("./train.json", "r"))
np_train = np.asarray(train["states"])
np_labels = np.asarray(train["labels"])
test = json.load(open("./test.json", "r"))
np_test_data = np.asarray(test["states"])

In [12]:
road_predic = gnb.fit(np_train, np_labels).predict(np_test_data)

In [21]:
print(len(np_test_data))
1 - (np.asarray(test["labels"] != road_predic).sum()) / float(len(np_test_data))

250


0.84399999999999997

## build gnb from scrach

### first calculate the mean and standard devivation, of each feature for each class

In [23]:
labels = set(np_labels)
labels

{u'keep', u'left', u'right'}

In [26]:
params = {}
for l in labels:
  params[l] = {
    "mean": np.mean(np_train[np_labels == l], axis=0),
    "std": np.std(np_train[np_labels == l], axis=0)
  }
params

{u'keep': {'mean': array([  2.03242493e+01,   3.68023986e+00,   9.99853891e+00,
           5.81203695e-03]),
  'std': array([ 11.43629681,   3.40382091,   1.06862615,   0.16812597])},
 u'left': {'mean': array([ 19.71413384,   5.05180597,   9.91412577,  -0.96708726]),
  'std': array([ 12.28989221,   2.3601083 ,   0.99023872,   0.66328201])},
 u'right': {'mean': array([ 19.47718534,   2.93404946,   9.94717186,   0.9540219 ]),
  'std': array([ 12.08546652,   2.31228006,   0.95208539,   0.64684464])}}

### calculate the likelihood of each feature

In [33]:
def gaussian(x, mean, var):
  return np.exp(- np.square(x - mean) / (2 * var)) / np.sqrt( 2 * np.pi * var)

In [48]:
keep_mean = params["keep"]["mean"]
keep_var = params["keep"]["std"]
keep_mean, keep_var
# [x for x in np_train[:, 0]]

[gaussian(x, keep_mean[0], keep_var[0]) for x in np_train[:, 0]]


# [lambda x: ]

[1.2897580558363978e-05,
 8.6542520131633885e-09,
 0.0022235686310883673,
 4.6866609593223273e-06,
 0.0004765674570976333,
 0.0046458203217722913,
 0.00058784901805799942,
 0.081823989578040782,
 0.10187101144169475,
 0.078900994454667417,
 0.030581380804035725,
 2.6081100667380637e-05,
 0.021129280310847983,
 0.027349575182538215,
 0.0022013407624274501,
 0.11153258971372758,
 0.009788135925451252,
 0.11796077767460204,
 5.8967013453962247e-10,
 0.021667617085623737,
 0.11722931844688497,
 0.0051505128600190441,
 0.087155351666242845,
 6.3371363987742901e-05,
 0.00055688441758538782,
 0.0033131177429556236,
 0.0045569808385822119,
 3.1538657984805606e-07,
 2.1303211109648809e-07,
 0.032552388143657442,
 0.0022475568813703521,
 0.00032738600613921873,
 0.0039445806173354254,
 9.2312783149757987e-08,
 0.0012325074365109002,
 0.0011134828267062723,
 0.090815492356313157,
 7.2031928578304528e-08,
 0.00066807703531311755,
 5.8060250786781122e-05,
 3.960710888109342e-07,
 0.0379492674869184

In [41]:
print(np.exp2(3))
print(np.exp(0) / np.sqrt(2 * np.pi))


print(gaussian(0, 0, 1))

np.square(2)
# np.var()

8.0
0.398942280401
0.398942280401


4

In [16]:
len(np_labels[np_labels == "left"]), len(np_labels[np_labels == "right"]), len(np_labels[np_labels == "keep"])

(214, 220, 316)

In [24]:
np_train_left = np_train[np_labels == "left"]

In [33]:
sum(np_train_left[:,0]) / 214

19.714133843021123

In [28]:
np.mean(np_train_left, axis=0)

array([ 19.71413384,   5.05180597,   9.91412577,  -0.96708726])

In [29]:
np.std(np_train_left, axis=0)

array([ 12.28989221,   2.3601083 ,   0.99023872,   0.66328201])

In [3]:
train.keys()

[u'states', u'labels']

In [4]:
len(train["states"])

750

In [6]:
train["states"][0], train["labels"][0]

([34.76807295828066,
  0.8329138124321809,
  8.206638634642987,
  -0.9989611424577053],
 u'left')